[package]
name = "ssz_types"
version = "1.0.0-beta.0"
edition = "2021"
description = "List, vector and bitfield types for SSZ"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/sigp/ssz_types"
documentation = "https://docs.rs/ssz_types"
keywords = ["ethereum"]
categories = ["cryptography::cryptocurrencies"]

[dependencies]
tree_hash = "1.0.0-beta.0"
ethereum_ssz = "1.0.0-beta.0"
ethereum_serde_utils = "1.0.0-beta.0"
serde = "1.0.0"
serde_derive = "1.0.0"
typenum = "1.12.0"
derivative = "2.1.1"
smallvec = "1.8.0"
arbitrary = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0.0"
tree_hash_derive = "1.0.0-beta.0"
